### ISSUE TITLE
Doppelgangers algorithm does not solve the Colmap problem

### ISSUE THREAD

**Issue by JohannesKrueger** [RuojinCai/doppelgangers#16]
Hello, i tried to fix the doppelganger error that occurs in the Colmap mapping process. I tested the doppelgangers algorithm in total with 3 different thresholds 0.7, 0.3 and 0.05 and there was no real optimization at any of them. Did I do something wrong?

Command used: 

`python script_sfm_disambiguation.py doppelgangers/configs/test_configs/sfm_disambiguation_example.yaml --colmap_exe_command colmap --input_image_path doppelgangers\datasets\8wuda87s\input --output_path doppelgangers\datasets\8wuda87s\output --threshold 0.05 --pretrained weights/doppelgangers_classifier_loftr.pt`

**Comment by RuojinCai** [comment]
Hello, the algorithm filters out more pairs when the threshold increases, since for the classifier, the prediction of probability for a pair closer to 1 is more likely to be a real matching pair, while a probability closer to 0 suggests a doppelgangers pair. You could try testing again with a higher threshold than 0.7 to filter more potential doppelganger pairs.
