### ISSUE TITLE
The script for SfM disambiguation

### ISSUE THREAD

**Issue by XYQ0121** [RuojinCai/doppelgangers#5]
Thanks for your great work!

But I have a question: In the sfm reconstruction script, feature extraction and matching were first performed using colmap, and then feature extraction and feature matching were performed using Loftr for the matched images. What is the purpose of doing this? Are the feature points and matches used in the sparse reconstruction process extracted by colmap or by Loftr?

I will be very appreciate if you can answer my question!

**Comment by awarebayes** [comment]
Same question, it would be nice to include an example for hloc, since colmap is very outdated by this point compared to hloc

**Comment by RuojinCai** [comment]
Thank you for your question. 

> But I have a question: In the sfm reconstruction script, feature extraction and matching were first performed using colmap, and then feature extraction and feature matching were performed using Loftr for the matched images. What is the purpose of doing this? 

We found that, in both pairwise doppelgangers classification and sfm disambiguation tasks, the model taking LoFTR matches as input has better performance than using SIFT+RANSAC matches generated by colmap as input. You can refer to the comparison in the ablation study (Table 3 in the paper).

>Are the feature points and matches used in the sparse reconstruction process extracted by colmap or by Loftr?

It uses feature points and matches extracted by colmap in the following sparse reconstruction process.

>Same question, it would be nice to include an example for hloc, since colmap is very outdated by this point compared to hloc

After discussing with @sarlinpe, we think it will be more practical to integrate our doppelgangers classifier into hloc, if the model takes sparse matches like SuperPoint+LightGlue as input, instead of dense matches like LoFTR. This requires training a new classifier with sparse matches.
